Phi = '(2 + 0.01 * t^2) * y';
t0 = 0;
T = 15;
y0 = 4;
n = 15;
[t, y1] = Euler_f(Phi, t0, T, y0, n);
semilogy(t, y1, '.g');
hold on;
[t, y3] = Taylor_sec(Phi, '0.02*t*y','2+0.01*t^2',t0, T, y0, n);
semilogy(t, y3, 'om');
[t, y4] = Henu(Phi, t0, T, y0, n);
semilogy(t, y4, '*c');
[t, y5] = Adams(Phi, t0, T, y0, n);
semilogy(t, y5, '+r');
[t, y6] = Runge_Kutta_mid(Phi, t0, T, y0, n);
semilogy(t, y6, '--xk');
[t, y7] = Runge_Kutta_quad(Phi, t0, T, y0, n);
semilogy(t, y7, '--b');
y = 4 * exp(2 * t + 0.005 * t.^2);
semilogy(t, y, 'xk');
xlabel('t');
ylabel('y(t)');
legend("Euler's method","second-order Taylor's method", "Heun's method.","two-step Adams-Bashforth method", "Runge-Kutta using mid-point", "fourth-order Runge-Kutta method", "exact");